config/routes.rb
Rails.application.routes.draw do
  root 'dogs#create'

  resources :visits
  resources :hydrants
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many :visits
  has_many :hydrants, through: :visits
end

app/models/hydrant.rb
class Hydrant < ApplicationRecord
  has_many :visits
  has_many :dogs, through: :visits

  def owner
    return '' unless visits.any?
    visits.pluck(:points).max.dog
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :dog
  belongs_to :hydrant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_dog
    Dog.find_by(id: session[:dog_id])
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  def create
    if current_dog.blank?
      dog = Dog.create({
        name: 'dog' + SecureRandom.uuid.to_s,
        level: 1,
        points: 0,
        stamina: 100,
        image: 'https://www.what-dog.net/Images/faces2/scroll0015.jpg'
      })
      dog.update(name: 'dog-' + dog.id.to_s)
      session[:dog_id] = dog.id
    end
    redirect_to current_dog
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show; end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dog
    @dog = Dog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dog_params
    params.require(:dog).permit(:name, :level, :points, :stamina, :image)
  end
end

app/controllers/hydrants_controller.rb
class HydrantsController < ApplicationController
  before_action :set_hydrant, only: [:show, :edit, :update, :destroy]

  # GET /hydrants
  # GET /hydrants.json
  def index
    @hydrants = Hydrant.all
  end

  # GET /hydrants/1
  # GET /hydrants/1.json
  def show
  end

  # GET /hydrants/new
  def new
    @hydrant = Hydrant.new
  end

  # GET /hydrants/1/edit
  def edit
  end

  # POST /hydrants
  # POST /hydrants.json
  def create
    @hydrant = Hydrant.new(hydrant_params)

    respond_to do |format|
      if @hydrant.save
        format.html { redirect_to @hydrant, notice: 'Hydrant was successfully created.' }
        format.json { render :show, status: :created, location: @hydrant }
      else
        format.html { render :new }
        format.json { render json: @hydrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hydrants/1
  # PATCH/PUT /hydrants/1.json
  def update
    respond_to do |format|
      if @hydrant.update(hydrant_params)
        format.html { redirect_to @hydrant, notice: 'Hydrant was successfully updated.' }
        format.json { render :show, status: :ok, location: @hydrant }
      else
        format.html { render :edit }
        format.json { render json: @hydrant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hydrants/1
  # DELETE /hydrants/1.json
  def destroy
    @hydrant.destroy
    respond_to do |format|
      format.html { redirect_to hydrants_url, notice: 'Hydrant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hydrant
      @hydrant = Hydrant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hydrant_params
      params.require(:hydrant).permit(:dog_id, :image)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:dog_id, :hydrant_id, :stamina_used)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/hydrants_helper.rb
module HydrantsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/dogs/_form.html.erb
<%= form_with(model: dog, local: true) do |form| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :dog_name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level, id: :dog_level %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points, id: :dog_points %>
  </div>

  <div class="field">
    <%= form.label :stamina %>
    <%= form.number_field :stamina, id: :dog_stamina %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Points</th>
      <th>Stamina</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.level %></td>
        <td><%= dog.points %></td>
        <td><%= dog.stamina %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>
<head>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
  <div class="container">
  	<div class="row">
		   <div class="col-lg-10 col-sm-6 text-center mt-3">
            <div class="card">
               <img class="card-img-top" src="<%= @dog.image %>" alt="Card image">
              <h2 class="card-header">Name: <%= @dog.name %></h2>
              <div class="card-body">Level: <%= @dog.level %></div>
              <div class="card-body">Hydrants Controlled: <%= @dog.visits.count %></div>
              <div class="card-body">Total Points: <%= @dog.points %></div>
              <div class="card-footer">Stamina: <%= @dog.stamina %></div>
            </div>
          <br>
          <h2>View Hydrants</h2>
      </div>
	 </div>
  </div>
</body>

app/views/hydrants/_form.html.erb
<%= form_with(model: hydrant, local: true) do |form| %>
  <% if hydrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hydrant.errors.count, "error") %> prohibited this hydrant from being saved:</h2>

      <ul>
      <% hydrant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dog_id %>
    <%= form.text_field :dog_id, id: :hydrant_dog_id %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :hydrant_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hydrants/edit.html.erb
<h1>Editing Hydrant</h1>

<%= render 'form', hydrant: @hydrant %>

<%= link_to 'Show', @hydrant %> |
<%= link_to 'Back', hydrants_path %>

app/views/hydrants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hydrants</h1>

<table>
  <thead>
    <tr>
      <th>Dog</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hydrants.each do |hydrant| %>
      <tr>
        <td><%= hydrant.dog %></td>
        <td><%= hydrant.image %></td>
        <td><%= link_to 'Show', hydrant %></td>
        <td><%= link_to 'Edit', edit_hydrant_path(hydrant) %></td>
        <td><%= link_to 'Destroy', hydrant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hydrant', new_hydrant_path %>

app/views/hydrants/new.html.erb
<h1>New Hydrant</h1>

<%= render 'form', hydrant: @hydrant %>

<%= link_to 'Back', hydrants_path %>

app/views/hydrants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dog:</strong>
  <%= @hydrant.dog %>
</p>

<p>
  <strong>Image:</strong>
  <%= @hydrant.image %>
</p>

<%= link_to 'Edit', edit_hydrant_path(@hydrant) %> |
<%= link_to 'Back', hydrants_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScentWars2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/visits/_form.html.erb
<%= form_with(model: visit, local: true) do |form| %>
  <% if visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dog_id %>
    <%= form.text_field :dog_id, id: :visit_dog_id %>
  </div>

  <div class="field">
    <%= form.label :hydrant_id %>
    <%= form.text_field :hydrant_id, id: :visit_hydrant_id %>
  </div>

  <div class="field">
    <%= form.label :stamina_used %>
    <%= form.number_field :stamina_used, id: :visit_stamina_used %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form', visit: @visit %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visits</h1>

<table>
  <thead>
    <tr>
      <th>Dog</th>
      <th>Hydrant</th>
      <th>Stamina used</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.dog %></td>
        <td><%= visit.hydrant %></td>
        <td><%= visit.stamina_used %></td>
        <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New Visit</h1>

<%= render 'form', visit: @visit %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dog:</strong>
  <%= @visit.dog %>
</p>

<p>
  <strong>Hydrant:</strong>
  <%= @visit.hydrant %>
</p>

<p>
  <strong>Stamina used:</strong>
  <%= @visit.stamina_used %>
</p>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>